<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <?= $this->headTitle('电商系统')->setSeparator(' - ')->setAutoEscape(false) ?>

  <?= $this->headLink(['rel'=>'stylesheet','href'=>'/assets/layui/css/layui.css']) ?>
    <script src="/assets/layui/layui.js"></script>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  

    <?= $this->partial('layout-layui/topBar.phtml', [

    ]); ?>


    <?= $this->partial('layout-layui/nav.phtml', [

    ]); ?>
  
  
  <div class="layui-body">
  
    <!-- 内容主体区域 -->
<div style="padding: 15px;">
    <span class="layui-breadcrumb">
    <a href="/">首页</a>
    <a href="/demo/">演示</a>
    <a><cite>导航元素</cite></a>
    </span>

        <?= $this->content ?>
	
	</div>
  </div>
  
  <div class="layui-footer">
    <!-- 底部固定区域 -->
    © layui.com - 底部固定区域
  </div>
</div>
<script>
//JavaScript代码区域
layui.use('element', function(){
  var element = layui.element;
  
});
</script>
</body>
</html>
      