<?= $this->doctype() ?>
<html>

<head>

    <?= $this->headTitle('电商系统')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('charset', 'utf-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel'=>'stylesheet','href'=>'/assets/css/amazeui.min.css']) ?>
    <?= $this->headLink(['rel'=>'stylesheet','href'=>'/assets/css/admin.css']) ?>
    <?= $this->headLink(['rel'=>'stylesheet','href'=>'/assets/css/app.css']) ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->appendFile($this->basePath('/assets/js/jquery.min.js'),'text/javascript')
        ->appendFile($this->basePath('/assets/js/amazeui.min.js'),'text/javascript')
//        ->appendFile($this->basePath('/assets/js/app.js'),'text/javascript')
    ?>

</head>

<body data-type="index">


<header class="am-topbar am-topbar-inverse admin-header">
    <div class="am-topbar-brand">
        <a href="javascript:;" class="tpl-logo">
            <img src="/assets/img/logo.png" alt="">
        </a>
    </div>
    <div class="am-icon-list tpl-header-nav-hover-ico am-fl am-margin-right">

    </div>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

    <?= $this->partial('layout/nav.phtml', [

    ]); ?>

</header>







<div class="tpl-page-container tpl-page-header-fixed">

    <?= $this->partial('layout/sideBar.phtml', [

    ]); ?>


    <div class="tpl-content-wrapper">

        <?= $this->partial('layout/topBar.phtml', [

        ]); ?>

        <?= $this->content ?>

    </div>

</div>

<div class="am-modal am-modal-no-btn" tabindex="-1" id="commom-modal">
    <div class="am-modal-dialog">
        <div class="am-modal-hd">Modal 标题
            <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
        </div>
        <div class="am-modal-bd">
            暂无内容
        </div>
    </div>
</div>

<script type="text/javascript" src="/assets/js/app.js"></script>
</body>

</html>

