<div class="tpl-left-nav tpl-left-nav-hover">
    <div class="tpl-left-nav-title">
        功能列表
    </div>
    <div class="tpl-left-nav-list">
        <ul class="tpl-left-nav-menu">
            <li class="tpl-left-nav-item">
                <a href="/" class="nav-link active">
                    <i class="am-icon-home"></i>
                    <span>仪表盘</span>
                </a>
            </li>
            <li class="tpl-left-nav-item">
                <a href="/chart" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-bar-chart"></i>
                    <span>统计报表</span>
                    <i class="tpl-left-nav-content tpl-badge-danger">
                        12
                    </i>
                </a>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-table"></i>
                    <span>商品管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu">
                    <li>
                        <a href="/goods/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商品基础信息</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/category/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商品分类管理</span>
                            <i class="tpl-left-nav-content tpl-badge-success">
                                18
                            </i>

                            <a href="/category/base">
                                <i class="am-icon-angle-right"></i>
                                <span>商品分类管理</span>
                                <i class="tpl-left-nav-content tpl-badge-primary">
                                    5
                                </i>


                                <a href="/goods/price">
                                    <i class="am-icon-angle-right"></i>
                                    <span>商品价格维护</span>

                                </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>商品库存系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/stock/base">
                            <i class="am-icon-angle-right"></i>
                            <span>库存管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/inventory/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商品盘存</span>
                        </a>

                        <a href="/loss/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商品报损</span>
                        </a>

                        <a href="/balance/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商品结存</span>
                        </a>

                        <a href="/bill/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商品出入库单</span>
                        </a>

                        <a href="/stock/frozen">
                            <i class="am-icon-angle-right"></i>
                            <span>商品不可售记录</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>商铺管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/shop/base">
                            <i class="am-icon-angle-right"></i>
                            <span>商铺管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/shop/goods">
                            <i class="am-icon-angle-right"></i>
                            <span>商铺商品管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/shop/distributor">
                            <i class="am-icon-angle-right"></i>
                            <span>配送员管理</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>供应商管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/supplier/base">
                            <i class="am-icon-angle-right"></i>
                            <span>供应商管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/supplier/goods">
                            <i class="am-icon-angle-right"></i>
                            <span>供应商供应商品管理</span>
                        </a>
                    </li>
                </ul>
            </li>


            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>采购商品管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/purchase/base">
                            <i class="am-icon-angle-right"></i>
                            <span>采购管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/purchase/bill">
                            <i class="am-icon-angle-right"></i>
                            <span>采购清单</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>调货管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/allocation/base">
                            <i class="am-icon-angle-right"></i>
                            <span>调货管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/allocation/mome">
                            <i class="am-icon-angle-right"></i>
                            <span>调货评论管理</span>
                        </a>
                    </li>
                </ul>
            </li>


            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>物流管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/logistics/send">
                            <i class="am-icon-angle-right"></i>
                            <span>物流配送</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/logistics/allocation">
                            <i class="am-icon-angle-right"></i>
                            <span>物流调拨</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>销售商品管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/saleBill/base">
                            <i class="am-icon-angle-right"></i>
                            <span>销售订单管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/sale/billMome">
                            <i class="am-icon-angle-right"></i>
                            <span>订单评论管理</span>
                        </a>
                    </li>
                </ul>
            </li>


            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>营销管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/marketing/favor">
                            <i class="am-icon-angle-right"></i>
                            <span>商品优惠</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>
                        <a href="/marketing/activity">
                            <i class="am-icon-angle-right"></i>
                            <span>商品活动</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>
                    </li>
                </ul>
            </li>


            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>用户管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/users/base">
                            <i class="am-icon-angle-right"></i>
                            <span>用户管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/users/point">
                            <i class="am-icon-angle-right"></i>
                            <span>用户积分</span>
                        </a>

                        <a href="/users/draw">
                            <i class="am-icon-angle-right"></i>
                            <span>用户画像</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>财务报表系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="form-amazeui.html">
                            <i class="am-icon-angle-right"></i>
                            <span>明细帐管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="form-line.html">
                            <i class="am-icon-angle-right"></i>
                            <span>总账管理</span>
                        </a>

                        <a href="form-line.html">
                            <i class="am-icon-angle-right"></i>
                            <span>账簿管理</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>账户管理系统</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/account/base">
                            <i class="am-icon-angle-right"></i>
                            <span>账户管理</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/account/auth">
                            <i class="am-icon-angle-right"></i>
                            <span>权限管理</span>
                        </a>
                    </li>
                </ul>
            </li>


            <li class="tpl-left-nav-item">
                <a href="javascript:;" class="nav-link tpl-left-nav-link-list">
                    <i class="am-icon-wpforms"></i>
                    <span>系统管理</span>
                    <i class="am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate"></i>
                </a>
                <ul class="tpl-left-nav-sub-menu" style="display: none;">
                    <li>
                        <a href="/system/application">
                            <i class="am-icon-angle-right"></i>
                            <span>应用列表</span>
                            <i class="am-icon-star tpl-left-nav-content-ico am-fr am-margin-right"></i>
                        </a>

                        <a href="/system/limit">
                            <i class="am-icon-angle-right"></i>
                            <span>应用限流配置</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>