<form class="layui-form" action="">

    <div class="layui-form-item">
    <label class="layui-form-label">上级类目</label>
        <div class="layui-input-block">
            <select name="quiz">
                <option value="">顶级</option>
                <optgroup label="烟酒饮料">
                    <option value="">烟</option>
                    <option value="">酒</option>
                    <option value="">饮料</option>
                </optgroup>
            </select>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">类目名称</label>
        <div class="layui-input-block">
            <input type="text" name="title" required  lay-verify="required" placeholder="类目名称" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">类目编号</label>
        <div class="layui-input-block">
            <input type="text" name="title" required  lay-verify="required" placeholder="类目编号" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">类目图片</label>
        <div class="layui-input-block">
            <button type="button" class="layui-btn" id="test2">类目图片上传</button>
            <blockquote class="layui-elem-quote layui-quote-nm" style="margin-top: 10px;">
                预览图：
                <div class="layui-upload-list" id="demo2"></div>
            </blockquote>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">类目属性</label>
        <div class="layui-input-block">
            <input type="checkbox" name="like[write]" title="热门">
            <input type="checkbox" name="like[read]" title="冷门" checked>
            <input type="checkbox" name="like[dai]" title="长周期">
        </div>
    </div>


    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">保存</button>
        </div>
    </div>
</form>

<script>
    //Demo
    layui.use('form', function(){
        var form = layui.form;

        //监听提交
        form.on('submit(formDemo)', function(data){
            layer.msg(JSON.stringify(data.field));
            return false;
        });
    });

    layui.use('upload', function() {
        var $ = layui.jquery
            , upload = layui.upload;

        //多图片上传
        upload.render({
            elem: '#test2'
            ,url: '/upload/'
            ,multiple: true
            ,before: function(obj){
                //预读本地文件示例，不支持ie8
                obj.preview(function(index, file, result){
                    $('#demo2').append('<img src="'+ result +'" alt="'+ file.name +'" class="layui-upload-img">')
                });
            }
            ,done: function(res){
                //上传完毕
            }
        });

    });

</script>