<div class="tpl-portlet-components">
    <div class="portlet-title">
        <div class="caption font-green bold">
            <span class="am-icon-code"></span> 添加商品
        </div>
        <div class="tpl-portlet-input tpl-fz-ml">
            <div class="portlet-input input-small input-inline">
                <div class="input-icon right">
                    <i class="am-icon-search"></i>
                    <input type="text" class="form-control form-control-solid" placeholder="搜索..."> </div>
            </div>
        </div>


    </div>
    <div class="tpl-block ">

        <div class="am-g tpl-amazeui-form">


            <div class="am-u-sm-12 am-u-md-9">
                <form method="post" class="am-form am-form-horizontal" action="<?= $this->url('goods', ['action' => 'add']) ?>">
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label">类目 </label>
                        <div class="am-u-sm-9">
                            <select data-am-selected="{searchBox: 1}">
                                <option value="a">休闲零食</option>
                                <option value="b">水果生鲜</option>
                                <option value="o">Orange</option>
                                <option value="m">Mango</option>
                                <option value="phone">iPhone</option>
                                <option value="im">iMac</option>
                                <option value="mbp">Macbook Pro</option>
                            </select>
                            <small>商品类目</small>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-email" class="am-u-sm-3 am-form-label">商品名称 </label>
                        <div class="am-u-sm-9">
                            <input type="email" id="user-email" name="goodsTitle" placeholder="商品名称">
                            <small>商品名称...</small>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-phone" class="am-u-sm-3 am-form-label">商品子标题 </label>
                        <div class="am-u-sm-9">
                            <input type="tel" id="user-phone" name="goodsSubTitle" placeholder="商品子标题 ">
                        </div>
                    </div>

                    <div class="am-form-group am-form-file">
                        <label for="user-phone" class="am-u-sm-3 am-form-label">商品图片 </label>
                        <div class="am-u-sm-9">
                        <button type="button" class="am-btn am-btn-danger am-btn-sm">
                            <i class="am-icon-cloud-upload"></i> 选择要上传的图片</button>
                            <input id="doc-form-file" type="file" multiple>
                            <div id="file-list"></div>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-QQ" class="am-u-sm-3 am-form-label">条码</label>
                        <div class="am-u-sm-9">
                            <input type="number" name="barcode" pattern="[0-9]*" id="user-QQ" placeholder="条码">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-weibo" class="am-u-sm-3 am-form-label">市场价 </label>
                        <div class="am-u-sm-9">
                            <input type="text" id="user-weibo" placeholder="市场价 ">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-intro" class="am-u-sm-3 am-form-label">标签 </label>
                        <div class="am-u-sm-9">
                            <textarea class="" rows="5" name="tags" id="user-intro" placeholder="标签"></textarea>
                            <small>标签...</small>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-weibo" class="am-u-sm-3 am-form-label">模式 </label>
                        <div class="am-u-sm-9">
                            <select name="mode" >
                                <option value="option1">自营</option>
                                <option value="option2">联营</option>
                            </select>
                        </div>
                    </div>


                    <div class="am-form-group">
                        <label for="user-weibo" class="am-u-sm-3 am-form-label">  保质期（天） </label>
                        <div class="am-u-sm-9">
                            <input type="text" name="qualityDate" id="user-weibo" placeholder="  保质期（天）">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <div class="am-u-sm-9 am-u-sm-push-3">
                            <button type="submit" class="am-btn am-btn-primary">保存修改</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
    $(function() {
        $('#doc-form-file').on('change', function() {
            var fileNames = '';
            $.each(this.files, function() {
                fileNames += '<span class="am-badge">' + this.name + '</span> ';
            });
            $('#file-list').html(fileNames);
        });
    });
</script>