<form class="layui-form" method="post" action="<?= $this->url('goods',['action'=>'add'])?>">
    <div class="layui-form-item">
        <label class="layui-form-label">商品名称</label>
        <div class="layui-input-block">
            <input type="text" name="title" required  lay-verify="required" placeholder="商品名称" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">商品子标题</label>
        <div class="layui-input-block">
            <input type="text" name="subTitle" required  lay-verify="required" placeholder="商品名称" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">类目</label>
        <div class="layui-input-block">
            <select name="categoryId" lay-verify="required">
                <option value="1">烟酒饮料</option>
                <option value="2">水果生鲜</option>
            </select>
        </div>
    </div>

    <div class="layui-form-item">
            <label class="layui-form-label">市场价</label>
            <div class="layui-input-block" style="width: 100px;">
                <input name="originalPrice" placeholder="￥" autocomplete="off" class="layui-input" type="text">
            </div>
    </div>


    <div class="layui-form-item">
        <label class="layui-form-label">商品图片</label>
        <div class="layui-input-block">
            <button type="button" class="layui-btn" id="test2">商品图片上传</button>
            <blockquote class="layui-elem-quote layui-quote-nm" style="margin-top: 10px;">
                预览图：
                <div class="layui-upload-list" id="demo2"></div>
            </blockquote>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">模式</label>
        <div class="layui-input-block">
            <select name="mode" lay-verify="required">
                <option value="1">自营</option>
                <option value="2">联营</option>
            </select>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">商品类型</label>

        <div class="layui-input-block">
            <input name="type" value="新品" title="新品" checked="" type="radio">
            <input name="type" value="临期" title="临期" type="radio">
            <input name="type" value="淘汰" title="淘汰" type="radio">
        </div>
    </div>


    <div class="layui-form-item">
        <label class="layui-form-label">是否生效</label>
        <div class="layui-input-block">
            <input type="checkbox" name="isShow" lay-skin="switch">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">商品标签</label>
        <div class="layui-input-block">
            <input type="text" name="tags" required  lay-verify="required" placeholder="商品标签以；分割" autocomplete="off" class="layui-input">
        </div>
    </div>


    <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">商品详情</label>
        <div class="layui-input-block">
            <textarea name="desc" placeholder="请输入内容" class="layui-textarea"></textarea>
        </div>
    </div>


    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" >保存</button>
        </div>
    </div>
</form>

<script>
    //Demo
    layui.use('form', function(){
        var form = layui.form;
        var $ = layui.jquery;

        //监听提交
        form.on('submit(formDemo)', function(data){
            // layer.msg(JSON.stringify(data.field));
            $.ajax({
                url: "<?= $this->url('goods',['action'=>'add'])?>",
                contentType: "application/json",
                data: data.field, //请求的附加参数，用json对象
                method: 'POST',
                success: function (res) {
                    if (res.status == true) {
                        layer.msg("添加成功", { icon: 6, time: 2000 }, function () {

                        });
                    }
                    else {
                        layer.msg("添加失败", { icon: 5 });
                    }

                },
                error: function () {
                    layer.msg("添加失败", { icon: 5 });
                }
            });
            return false;//只此一句
        });
    });

    layui.use('upload', function() {
        var $ = layui.jquery
            , upload = layui.upload;

        //多图片上传
        upload.render({
            elem: '#test2'
            ,url: '/upload/'
            ,multiple: true
            ,before: function(obj){
                //预读本地文件示例，不支持ie8
                obj.preview(function(index, file, result){
                    $('#demo2').append('<img src="'+ result +'" alt="'+ file.name +'" class="layui-upload-img">')
                });
            }
            ,done: function(res){
                //上传完毕
            }
        });

    });

</script>