<fieldset class="layui-elem-field layui-field-title">
  <legend>商品信息</legend>
</fieldset>

<form class="layui-form" action="">
<div class="layui-form-item">

    <div class="layui-input-inline" style="width: 60px;">
    <a href="<?= $this->url('goods',['action'=>'add']) ?>" class="layui-btn ">新增</a>
    </div>
	
	<label  style="width:auto;" class="layui-form-label">名称</label>
    <div class="layui-input-inline">
      <input type="text" name="title" style="width:200px;" lay-verify="title" autocomplete="off" placeholder="请输入标题" class="layui-input">
    </div>
	
	<label style="width:auto;" class="layui-form-label">日期</label>
      <div class="layui-input-inline">
        <input type="text" name="date" id="date" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">
      </div>

	  <button class="layui-btn layui-btn-normal"><i class="layui-icon layui-icon-search"></i>  搜索</button>
</div>
</form>

<hr>
	
	
<div class="layui-form">
  <table class="layui-table">
    <colgroup>
      <col >
      <col >
      <col >
      <col >
      <col width="160" >
    </colgroup>
    <thead>
      <tr>
        <th>商品信息</th>
        <th>商品属性</th>
        <th>商品标签</th>
        <th>商品模式</th>
		<th>操作</th>
      </tr> 
    </thead>
    <tbody>
    <?php foreach ($list as $v){ ?>
        <tr>
            <td>
                <?= $v->title ?></br>

            </td>
            <td>
                规格：

                <ul>
                    <?php foreach ($v->specificat as $sp){ ?>
                    <li><?= $sp['name'] ?> （<?= $sp['units'] ?>）</li>
                    <?php } ?>
                </ul>
                市场价： ￥<?= $v->originalPrice/100 ?>

            </td>
            <td>
                <ul>
                    <?php foreach ($v->tags as $tag){ ?>
                    <li><?= $tag ?></li>
                    <?php } ?>
                </ul>
            </td>
            <td>
                是否自营： <?= $v->mode ?><br>
                商品类型： <?= $v->type ?><br>
            </td>
            <td>

                <div class="layui-btn-group">
                    <button class="layui-btn layui-btn-sm"><i class="layui-icon"></i></button>
                    <button class="layui-btn layui-btn-sm"><i class="layui-icon"></i></button>
                </div>
            </td>
        </tr>
    <?php }?>

    </tbody>
  </table>
</div>


<div id="demo0"></div>

<script>
    layui.use(['laypage', 'layer'], function(){
        var laypage = layui.laypage
            ,layer = layui.layer;
        //总页数低于页码总数
        laypage.render({
            elem: 'demo0'
            ,count: 50 //数据总数
        });
    });
</script>