<form class="layui-form" method="post" action="<?= $this->url('shop',['action'=>'add'])?>">
    <div class="layui-form-item">
        <label class="layui-form-label">店铺名称</label>
        <div class="layui-input-block">
            <input type="text" name="shopName" required  lay-verify="required" placeholder="店铺名称" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">店铺别名</label>
        <div class="layui-input-block">
            <input type="text" name="shopAlias" required  lay-verify="required" placeholder="店铺别名" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">店铺类型</label>
        <div class="layui-input-block">
            <select name="shopType" lay-verify="required">
                <option value="1">仓库</option>
                <option value="2">临售点</option>
            </select>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">店铺地址</label>
        <div class="layui-input-block">
            <input type="text" name="shopAddress" required  lay-verify="required" placeholder="店铺地址" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">电话</label>
        <div class="layui-input-block">
            <input type="text" name="shopTel" required  lay-verify="required" placeholder="电话" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">店铺负责人</label>
        <div class="layui-input-block">
            <input type="text" name="shopLeading" required  lay-verify="required" placeholder="店铺负责人" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">运费</label>
        <div class="layui-input-block" style="width: 100px;">
            <input name="shopLogic" placeholder="￥" autocomplete="off" class="layui-input" type="text">
        </div>
    </div>


    <div class="layui-form-item">
        <label class="layui-form-label">店铺展示图</label>
        <div class="layui-input-block">
            <button type="button" class="layui-btn" id="test2">商品图片上传</button>
            <blockquote class="layui-elem-quote layui-quote-nm" style="margin-top: 10px;">
                预览图：
                <div class="layui-upload-list" id="demo2"></div>
            </blockquote>
        </div>
        <div id="shopPic">

        </div>
    </div>


    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" >保存</button>
        </div>
    </div>
</form>

<script>
    //Demo
    layui.use('form', function(){
        var form = layui.form;
        var $ = layui.jquery;

        //监听提交
        form.on('submit(formDemo)', function(data){
            // layer.msg(JSON.stringify(data.field));
            $.ajax({
                url: "<?= $this->url('goods',['action'=>'add'])?>",
                contentType: "application/json",
                data: data.field, //请求的附加参数，用json对象
                method: 'POST',
                success: function (res) {
                    if (res.status == true) {
                        layer.msg("添加成功", { icon: 6, time: 2000 }, function () {

                        });
                    }
                    else {
                        layer.msg("添加失败", { icon: 5 });
                    }

                },
                error: function () {
                    layer.msg("添加失败", { icon: 5 });
                }
            });
            return false;//只此一句
        });
    });

    layui.use('upload', function() {
        var $ = layui.jquery
            , upload = layui.upload;

        //多图片上传
        upload.render({
            elem: '#test2'
            ,url: '/upload'
            ,multiple: true
            ,before: function(obj){
                //预读本地文件示例，不支持ie8
                obj.preview(function(index, file, result){
                    $('#demo2').append('<img src="'+ result +'" alt="'+ file.name +'" class="layui-upload-img">')
                });
            }
            ,done: function(res){
                $('#shopPic').append('<input type="hidden" name="shopPic" value="'+res.file+'">')
                //上传完毕
                layer.msg('上传成功',res);
            }
        });

    });

</script>