<div class="tpl-portlet-components">
<div class="portlet-title">
    <div class="caption font-green bold">
        <span class="am-icon-code"></span> 列表
    </div>
    <div class="tpl-portlet-input tpl-fz-ml">
        <div class="portlet-input input-small input-inline">
            <div class="input-icon right">
                <i class="am-icon-search"></i>
                <input type="text" class="form-control form-control-solid" placeholder="搜索..."> </div>
        </div>
    </div>


</div>
<div class="tpl-block">
    <div class="am-g">
        <div class="am-u-sm-3 am-u-md-3 am-u-lg-3">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    <a href="<?= $this->url('goods', ['action' => 'add']) ?>" type="button" class="am-btn am-btn-default am-btn-success "><span class="am-icon-plus"></span> 新增</a>
                    <button type="button" class="am-btn am-btn-default am-btn-secondary"><span class="am-icon-save"></span> 保存</button>
                    <button type="button" class="am-btn am-btn-default am-btn-warning"><span class="am-icon-archive"></span> 审核</button>
                    <button type="button" class="am-btn am-btn-default am-btn-danger"><span class="am-icon-trash-o"></span> 删除</button>
                </div>
            </div>
        </div>
        <div class="am-u-sm-9 am-u-md-9 am-u-lg-9" style="text-align: right;">
            <form class="am-form-inline" role="form">
                <div class="am-form-group">
                    <input type="text" class="am-form-field" placeholder="商品名"/>
                </div>
                &nbsp;
                <div class="am-form-group">
                    <input type="text" class="am-form-field" placeholder="sku"/>
                </div>
                &nbsp;
                <div class="am-form-group">
                    <select data-am-selected="{btnSize: 'sm'}">
                        <option value="option1">所有类别</option>
                        <option value="option2">IT业界</option>
                        <option value="option3">数码产品</option>
                        <option value="option3">笔记本电脑</option>
                        <option value="option3">平板电脑</option>
                        <option value="option3">只能手机</option>
                        <option value="option3">超极本</option>
                    </select>
                </div>
                &nbsp;
                <div class="am-form-group">
                    <button class="am-btn  am-btn-default am-btn-success tpl-am-btn-success am-icon-search" type="button"></button>
                </div>
            </form>
        </div>
    </div>
    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form">
                <table class="am-table am-table-striped am-table-hover table-main">
                    <thead>
                    <tr>
                        <th class="table-check"><input type="checkbox" class="tpl-table-fz-check"></th>
                        <th >店铺名称</th>
                        <th >店铺别名</th>
                        <th >店铺图片</th>
                        <th >是否营业</th>
                        <th>类型</th>
                        <th >店铺地址</th>
                        <th >店铺负责人</th>
                        <th >联系电话</th>
                        <th >店铺物流模式</th>
                        <th class="table-set">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php for ($i=1;$i<5;$i++) {?>
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>
                            金色池塘店
                        </td>
                        <td></td>
                        <td>

                        </td>
                        <td class="am-hide-sm-only">营业中</td>
                        <td class="am-hide-sm-only">零售店铺</td>
                        <td class="am-hide-sm-only">重庆市渝北区两路桂馥大道金色池塘13栋1―3</td>
                        <td class="am-hide-sm-only">139831568975</td>
                        <td class="am-hide-sm-only">未满20收取配送费2元</td>
                        <td>
                            <div class="am-btn-toolbar">
                                <div class="am-btn-group am-btn-group-xs">
                                    <a href="<?= $this->url('goods',['action'=>'edit','id'=>12]) ?>" class="am-btn am-btn-default am-btn-xs am-text-secondary"><span class="am-icon-pencil-square-o"></span> 编辑</a>
                                    <a class="am-btn am-btn-default am-btn-xs am-hide-sm-only"><span class="am-icon-copy"></span> 复制</a>
                                    <a url="<?= $this->url('goods',['action'=>'delete']) ?>" class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only js-modal-open"><span class="am-icon-trash-o"></span> 删除</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                     <?php } ?>
                    </tbody>
                </table>
                <div class="am-cf">

                    <div class="am-fr">
                        <ul class="am-pagination tpl-pagination">
                            <li class="am-disabled"><a href="#">«</a></li>
                            <li class="am-active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">»</a></li>
                        </ul>
                    </div>
                </div>
                <hr>

            </form>
        </div>

    </div>
</div>
<div class="tpl-alert"></div>
</div>

